#!/bin/sh /etc/rc.common

USE_PROCD=1

START=95
STOP=10

PROG="/usr/bin/ssserver"
CONFIG="/etc/shadowsocks-rust/config.json"

start_service() {
    [ -x "$PROG" ] || {
        logger -t shadowsocks-rust "ssserver not found"
        return 1
    }

    [ -f "$CONFIG" ] || {
        logger -t shadowsocks-rust "config not found"
        return 1
    }

    procd_open_instance
    procd_set_param command "$PROG" -c "$CONFIG"
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
