DEVICE_NAME="r5s"

TARGET="rockchip"
SUBTARGET="armv8"
PROFILE="friendlyarm_nanopi-r5s"

HOSTNAME="r5s"
LAN_IP="192.168.8.1"

PACKAGE_FILE="/custom-config/packages-r5s.txt"

IMAGE_PATTERN="friendlyarm_nanopi-r5s"